---

# Copyright (c) 2018 Kabolt
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Enable cron job for certbot renewal
  cron:
    name: Certbot automatic renewal
    user: "{{ certbot_cron_user }}"
    job: "{{ certbot_cron_random_sleep_cmd }}{{ certbot_executable }} renew {{ certbot_cron_autorenew_options }}"
    minute: "{{ certbot_cron_minute }}"
    hour: "{{ certbot_cron_hour }}"
    day: "{{ certbot_cron_dayofmonth }}"
    month: "{{ certbot_cron_month }}"
    weekday: "{{ certbot_cron_dayofweek }}"
    cron_file: ansible_cron_cerbot
  when: certbot_cron_autorenew

- name: Disable default cron job from certbot package
  file:
    path: /etc/cron.d/certbot
    state: absent

- name: Disable cron job for certbot renewal
  cron:
    name: Certbot automatic renewal
    cron_file: ansible_cron_cerbot
    state: absent
  when: not certbot_cron_autorenew
