---

# Copyright (c) 2018 Hexanode
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# OS support verification
- name: Check OS support
  fail:
    msg: "Unsupported OS for certbot role. Currently supported : Debian 9,10 & 11"
  when: >
    (ansible_distribution != 'Debian')
    or
    (ansible_distribution == 'Debian' and (ansible_distribution_major_version is version('9', '<') or ansible_distribution_major_version is version('11', '>')))

# Install
- name: Static import of install
  import_tasks: install.yml
  tags: certbot_install

# Config
- name: Static import of config
  import_tasks: config.yml
  tags: certbot_config
