---

# Copyright (c) 2018 Hexanode
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "Check if certificate already exists for {{ item }}"
  stat:
    path: "/etc/letsencrypt/live/{{ item }}/cert.pem"
  register: certificate_revoke

- name: "Revoke certificate for {{ item }}"
  shell: "{{ certbot_executable }} revoke --cert-path /etc/letsencrypt/live/{{ item }}/cert.pem"
  when: certificate_revoke.stat.exists

- name: "Delete certificate for {{ item }}"
  shell: "{{ certbot_executable }} delete --cert-name {{ item }}"
  when: certificate_revoke.stat.exists
